/**
 * lang.js — Bilingual support: English / Serbian (Latin)
 * Usage:  t('key')          → translated string in active language
 *         setLang('sr')     → switch to Serbian + re-render
 *         applyI18n()       → update all [data-i18n] elements in DOM
 */

const TRANSLATIONS = {
    en: {
        /* ── App shell ── */
        appTitle:           'FPL Team Analyzer',
        appEyebrow:         'Fantasy Premier League',
        analysis:           'Analysis',
        footerText:         'Made with',
        footerBy:           'for you by',
        footerHtml:         'Made with <span class="heart">&#x2665;</span> for you by <strong>Srdjan Kojic</strong>',
        dark:               'Dark',
        light:              'Light',
        close:              'Close',
        back:               '←',

        /* ── Card titles ── */
        cardMyTeam:         'My Team',
        cardPerformance:    'Performance Analytics',
        cardDatabase:       'Player Database',
        cardPrediction:     'Points Prediction',
        cardTransfers:      'Transfer Suggestions',
        cardComparison:     'Player Comparison',

        /* ── Loading / error ── */
        loading:            'Loading...',
        loadingTeam:        'Loading team data...',
        loadingPerf:        'Loading performance data...',
        loadingPlayers:     'Loading players...',
        loadingPredictions: 'Calculating predictions...',
        loadingTransfers:   'Analyzing transfers...',
        loadingComparison:  'Loading comparison...',
        errorTeam:          'Error loading team data',
        errorPerf:          'Error loading performance data',
        errorTransfers:     'Error loading transfer suggestions',
        errorPredictions:   'Error calculating predictions',

        /* ── My Team / pitch ── */
        gameweek:           'Gameweek',
        substitutes:        'Substitutes',
        flagInjured:        'Injured',
        flagSuspended:      'Suspended',
        flagUnavailable:    'Unavailable',
        flagDoubtful:       'Doubtful',
        gwPoints:           'GW Points',
        bank:               'Bank',
        teamValue:          'Team Value',
        captain:            'C',
        viceCaptain:        'VC',
        pts:                'pts',

        /* ── Player Database table ── */
        searchPlaceholder:  'Search players by name, team, or position...',
        allPositions:       'All Positions',
        allTeams:           'All Teams',
        goalkeeper:         'Goalkeeper',
        defender:           'Defender',
        midfielder:         'Midfielder',
        forward:            'Forward',
        colName:            'Name',
        colTeam:            'Team',
        colPosition:        'Position',
        colPrice:           'Price',
        colPoints:          'Points',
        colForm:            'Form',
        colGoals:           'Goals',
        colAssists:         'Assists',
        colXGI:             'Exp. G+A',
        colTackles:         'Tackles',
        colOwned:           'Owned By%',
        showingPlayers:     'Showing',
        players:            'players',
        noPlayersFound:     'No players found',

        /* ── Performance Analytics ── */
        perfTitle:          'Performance Analytics',
        perfSubtitle:       'Season Overview',
        gwHistory:          'Gameweek History',
        gwPointsChart:      'Points per Gameweek',
        totalPoints:        'Total Points',
        overallRank:        'Overall Rank',
        bestGW:             'Best GW',
        worstGW:            'Worst GW',
        totalTransfers:     'Total Transfers',
        rank:               'Rank',
        transfers:          'Transfers',
        gwsPlayed:          'GWs Played',
        seasonStats:        'Season Statistics',

        /* ── Predictions ── */
        predTitle:          'Points Prediction',
        predSubtitle:       'Next 5 Gameweeks Analysis',
        expectedPoints:     'Expected Points',
        captainRec:         'Captain Recommendation',
        nextGWPredictions:  'Next Gameweek Predictions',
        topPerformers:      'Top Expected Performers',
        allPlayersPred:     'All Players - Expected Points',
        top3Fixture:        'Top 3 Players - Fixture Analysis',
        xPts:               'xPts',
        form:               'Form',
        rising:             'Rising',
        falling:            'Falling',
        stable:             'Stable',

        /* ── Transfers ── */
        transferTitle:      'Transfer Suggestions',
        transferSubtitle:   'Optimize Your Team',
        transferAnalysis:   'Transfer Analysis',
        budgetAvail:        'Budget Available',
        transfersGW:        'Transfers This GW',
        freeTransfers:      'Free Transfers',
        verdictMake:        'Make it',
        verdictHit:         'Worth a −4',
        verdictMarginal:    'Marginal: consider rolling',
        alternativesNote:   'Alternatives: each uses one transfer',
        sellPrice:          'sell',
        fixturesXPts:       'Fixtures & Projected Points',
        planTitle:          'Transfer Plan',
        planVsRoll:         'vs rolling every week',
        planRoll:           'Roll transfer',
        planFT:             'FT',
        planXI:             'XI',
        planCaptain:        'Captain',
        planBan:            'Never buy this player',
        planLockHint:       'Lock players to keep (never sold):',
        planBanned:         'Never bought (click to allow again):',
        singleTransfers:    'Best Single Transfers',
        planNext:           'Plan',
        cardLeague:         'Mini-League',
        leagueSelect:       'League',
        leagueStandings:    'Standings',
        leagueThreats:      'Threats: owned by rivals, not (enough) by you',
        leagueDiffs:        'Your Differentials',
        leagueCaptains:     'Rivals\' Captains',
        leagueTemplate:     'Template: owned by half the league or more',
        leagueExplain:      '<strong>EO (effective ownership)</strong> = how much of a player\'s points the average rival collects: 100% per starting owner, 200% per captain, divided by the number of rivals. Every point a player scores moves you by <em>your multiplier − EO</em> against the average rival; <strong>swing</strong> is that times his projected points for the next gameweek.',
        leagueBasedOn:      'Lineups from GW',
        leagueSampled:      'rivals analysed',
        leagueTop50:        'large league: top 50 only',
        leagueNone:         'You are not in any classic league yet.',
        leagueYou:          'You',
        leagueGap:          'Gap',
        leagueGW:           'GW',
        leagueTotal:        'Total',
        leagueRank:         'Rank',
        leagueManager:      'Manager',
        leagueSwing:        'Swing',
        leagueYours:        'You',
        leagueChips:        'Chips played',
        errorLeague:        'Error loading league data',
        loadingLeague:      'Loading league...',
        leagueTopOverall:   'Overall top {n} managers (updated each gameweek)',
        cardFixtures:       'Fixture Analyser',
        fxAttack:           'Attack: expected goals',
        fxDefence:          'Defence: clean sheet %',
        fxFdr:              'FPL difficulty',
        fxSortNext:         'Sort by next',
        fxBlank:            'Blank',
        fxNone:             'No upcoming fixtures.',
        fxExplain:          'Expected goals and clean-sheet chances come from each team\'s xG for and against this season (blended with FPL\'s rating early on) and home advantage, so they separate a good fixture for attackers from a good one for defenders, which the 1–5 FPL difficulty cannot. Doubles add up; a blank gameweek counts as nothing. • = blended with bookmaker odds (next matches only).',
        fxBestAttack:       'Best attacking runs',
        fxBestDefence:      'Best defensive runs',
        errorFixtures:      'Error loading fixtures',
        loadingFixtures:    'Loading fixtures...',
        cardOptimizer:      'AI Team & Chips',
        opLoading:          'Optimizing squads...',
        opRating:           'AI Team Rating',
        opRatingExplain:    'Your squad\'s projected points ({range}, best XI + captain each week) as a share of the best squad the optimizer finds for your budget of £{budget}m (bank + selling prices).',
        opPts:              'pts',
        opVsYours:          'vs your squad',
        opChanges:          'changes',
        opOut:              'Out',
        opCalendar:         'Chip Calendar',
        opCalendarExplain:  'Value of each chip you still have, per gameweek, with your current squad: Bench Boost = your bench\'s points, Triple Captain = your captain\'s points once more, Free Hit = best one-week squad minus your XI. Later weeks assume no transfers, so use them as a guide. The first set of chips must be used by GW{deadline}. Best week per chip is highlighted.',
        opNoSpecial:        'No blank or double gameweeks are scheduled in this window yet; chip values are similar from week to week. Doubles usually appear when cup fixtures move matches.',
        opXI:               'Your XI',
        opDoubles:          'Doubles',
        opBlanks:           'Blanks',
        opYours:            'yours',
        opBestWeeks:        'Best weeks',
        chipWildcard:       'Wildcard',
        chipFreeHit:        'Free Hit',
        chipBenchBoost:     'Bench Boost',
        chipTripleCaptain:  'Triple Captain',
        errorOptimizer:     'Error running the optimizer',
        cardPrices:         'Price Changes',
        pcExplain:          'From FPL\'s own price predictor: each player\'s progress towards the next price change, where +100% means a rise and −100% a fall. <em>Tonight</em> is the projection for the next change window (around midnight UK time). A price can change at most once a day. Your selling price only rises by half of any increase.',
        pcYourSquad:        'Your Squad',
        pcSquadAlert:       'Expected to change tonight',
        pcRisers:           'Likely to rise',
        pcFallers:          'Likely to fall',
        pcRose:             'Rose this gameweek',
        pcFell:             'Fell this gameweek',
        pcNow:              'Now',
        pcTonight:          'Tonight',
        pcThisGW:           'This GW',
        pcNetTransfers:     'Net transfers',
        pcNone:             'None at the moment.',
        pcWatch:            'Watch tonight',
        errorPrices:        'Error loading prices',
        loadingPrices:      'Loading prices...',
        cardLive:           'Live Gameweek',
        lvInProgress:       'matches in progress, refreshing every minute',
        lvFinished:         'gameweek finished',
        lvBetween:          'between matches',
        lvNotStarted:       'not started yet',
        lvUpdated:          'updated',
        lvExplain:          'Live points with <strong>provisional bonus</strong> (*) from the bonus point system while a match\'s bonus isn\'t confirmed, and <strong>automatic substitutions</strong> once a starter\'s matches are over without him playing (↑ in, ↓ out). League totals include hits; ▲▼ is the change since the gameweek started.',
        lvYourTeam:         'Your Team',
        lvLeague:           'Live League Table',
        lvMins:             'Mins',
        lvProvisional:      'provisional bonus',
        lvPoints:           'Live points',
        errorLive:          'Error loading live points',
        loadingLive:        'Loading live points...',
        accTitle:           'Model Accuracy',
        accExplain:         'Backtest on {range} ({n} player-gameweeks): each gameweek is projected from the matches before it and compared with the points actually scored. Lower error and higher correlation are better.',
        accMae:             'Avg. error (pts)',
        accCorr:            'Correlation',
        accModel:           'This model',
        accPPG:             'Points per game',
        accForm:            'Recent form',
        accTop10:           'The model\'s top-10 projected players scored <strong>{model}</strong> pts on average per gameweek, vs <strong>{form}</strong> for the top 10 by form.',
        gkpOptions:         'GKP Options',
        outfieldOptions:    'Outfield Options',
        sortedByGain:       'Sorted by Expected Pts Gain',
        budget:             'Budget',
        noTransfers:        'No transfer suggestions at this time. Your team looks good!',
        perfectTeam:        '🎉 Perfect Team!',
        perfectTeamDesc:    'No significant transfer improvements found. Your squad is excellently optimized!',
        howCalc:            'How suggestions are calculated',
        howCalcBlock:       `<strong>How suggestions are calculated</strong><ul style="margin:6px 0 6px 18px; padding:0;"><li><strong>Projected points per gameweek</strong> for the next 5 deadlines (blanks score 0, doubles count both matches). Each match combines minutes (starts and minutes in recent matches and the season, injury news), goals and assists from xG/xA per 90, clean sheets and goals conceded from team strength, saves, defensive contributions, bonus and cards, using this season's FPL scoring.</li><li><strong>Team strength</strong> comes from each club's xG for and against this season, blended with FPL's own rating while the sample is small.</li><li><strong>Gain</strong> = how much your best XI plus captain improves over those gameweeks, with nearer gameweeks counting more. A bench player only adds points if he would start.</li></ul>Transfers respect your selling prices (you keep half of any price rise), your bank and the 3-per-club limit. Each option uses one transfer: with a free transfer it is worth making above ~2 pts; without one it must also cover the −4 hit.`,
        dbStatsBlock:       `<h4>📊 Comprehensive Player Statistics - 48 Data Points</h4><p><strong>How to use:</strong> Scroll horizontally to see all columns. Hover over any column header for detailed explanations. Click headers to sort.</p><p><strong>Data sources:</strong> Official FPL API + Opta Sports Analytics (trusted by Premier League, FIFA, UEFA)</p><p><strong>Categories:</strong> Basic Stats (8) • Performance Metrics (12) • Expected Stats (9) • Opta Advanced (7) • Set Pieces (3) • Transfer Trends (4) • Value Analysis (2) • Availability (1)</p><p style="margin-top:8px;"><strong>Color coding:</strong> <span class="legend-pill legend-green">Green = High performer</span> <span class="legend-pill legend-red">Red = Low form/injured</span> <span class="legend-pill legend-purple">Purple = High xGI</span> <span class="legend-pill legend-yellow">Yellow = Elite per 90</span> <span class="legend-pill legend-blue">Blue = ICT leader</span></p>`,
        topScorerLabel:     '🏆 TOP SCORER',
        bestFormLabel:      '🔥 BEST FORM',
        mostMinsLabel:      '⏱️ MOST MINUTES',
        mostGoalsLabel:     '⚽ MOST GOALS',
        mostAssistsLabel:   '🎯 MOST ASSISTS',
        mostKeyPassLabel:   '🔑 MOST KEY PASSES',
        mostTacklesLabel:   '🛡️ MOST TACKLES',
        bestXGILabel:       '📊 BEST xGI',
        goalsLabel:         'goals',
        assistsLabel:       'assists',
        passesLabel:        'passes',
        tacklesLabel:       'tackles',
        transferOut:        'OUT',
        transferIn:         'IN',
        transferReason:     'Reason',
        transferCost:       'Transfer Cost',
        newBudget:          'New Budget',
        next3Fixtures:      'Next 3 Fixtures Comparison',
        playersToWatch:     'Players to Watch',
        highPerformers:     'High-performing players across all positions:',
        option:             'Option',
        gkpFull:            'Goalkeepers',
        defFull:            'Defenders',
        midFull:            'Midfielders',
        fwdFull:            'Forwards',
        transferSuggHeader: 'Transfer Suggestions',
        transferSuggSuffix: ' Transfer Suggestions',
        valueLabel:         'Value',

        /* ── Player Comparison ── */
        cmpHint:            'Search and select up to 3 players to compare their FPL stats.',
        cmpPlayer1:         'Player 1...',
        cmpPlayer2:         'Player 2...',
        cmpPlayer3:         'Player 3 (optional)',
        cmpTitle:           'Player Comparison',

        /* ── Player page ── */
        playerTitle:        'Player Profile',
        upcomingFixtures:   'Upcoming Fixtures',
        recentGWPoints:     'Recent Gameweek Points',
        last10GWs:          'Last 10 Gameweeks',
        gwCol:              'GW',
        opponent:           'Opponent',
        homeAway:           'H/A',
        score:              'Score',
        mins:               'Mins',
        goals:              'G',
        assists2:           'A',
        cleanSheets:        'CS',
        yellow:             'Yel',
        ptsCol:             'Pts',
        attackStats:        'Attack',
        defenceStats:       'Defence',
        valueTransfers:     'Value & Transfers',
        price:              'Price',
        valueSeason:        'Value (Season)',
        valueForm:          'Value (Form)',
        gwTransIn:          'GW Transfers In',
        gwTransOut:         'GW Transfers Out',
        seasonIn:           'Season In',

        /* ── Guardian / Onboarding ── */
        guardianSubtitle:   'Your personal Fantasy Premier League intelligence hub',
        guardianInputLabel: 'Enter your FPL Team ID',
        guardianInputPlaceholder: 'e.g. 1234567',
        guardianContinue:   'Continue →',
        guardianHowTitle:   'How to find your Team ID',
        guardianStep1:      'Go to <strong>fantasy.premierleague.com</strong> and log in to your account',
        guardianStep2:      'Click <strong>“Points”</strong> in the top navigation menu',
        guardianStep3:      'Look at the URL bar — it will look like <code>/entry/<strong>1234567</strong>/event/1/</code>',
        guardianStep4:      'The number between <code>/entry/</code> and <code>/event/</code> is your Team ID',
        guardianTip:        '💡 Tip: Your Team ID is a 7-digit number visible in the URL on your FPL points page.',
        changeTeamId:       'Change ID',
        changeTeamIdTitle:  'Change FPL Team ID',
        changeTeamIdSave:   'Save & Reload',
        changeTeamIdCancel: 'Cancel',

        /* ── Misc ── */
        home:               'HOME',
        away:               'AWAY',
        h:                  'H',
        a:                  'A',
        diff:               'Diff',
        vs:                 'vs',
        at:                 '@',
        average:            'Avg',
        seasonAvg:          'Season Average',
        gwPointsLabel:      'GW Points',
        noInjuryNews:       'No injury news',
        last:               'Last',
        gameweeks:          'Gameweeks',
    },

    sr: {
        /* ── App shell ── */
        appTitle:           'FPL Analizator Tima',
        appEyebrow:         'Fantasy Premier Liga',
        analysis:           'Analiza',
        footerText:         'Napravljeno s',
        footerBy:           'za tebe od strane',
        footerHtml:         'Napravio za tebe od <span class="heart">&#x2665;</span> <strong>Srdjan Kojic</strong>',
        dark:               'Tamna',
        light:              'Svetla',
        close:              'Zatvori',
        back:               '←',

        /* ── Card titles ── */
        cardMyTeam:         'Moj Tim',
        cardPerformance:    'Analitika Performansi',
        cardDatabase:       'Baza Igrača',
        cardPrediction:     'Predikcija Poena',
        cardTransfers:      'Predlozi Transfera',
        cardComparison:     'Poređenje Igrača',

        /* ── Loading / error ── */
        loading:            'Učitavanje...',
        loadingTeam:        'Učitavanje podataka tima...',
        loadingPerf:        'Učitavanje analitike...',
        loadingPlayers:     'Učitavanje igrača...',
        loadingPredictions: 'Računanje predikcija...',
        loadingTransfers:   'Analiza transfera...',
        loadingComparison:  'Učitavanje poređenja...',
        errorTeam:          'Greška pri učitavanju tima',
        errorPerf:          'Greška pri učitavanju analitike',
        errorTransfers:     'Greška pri učitavanju transfera',
        errorPredictions:   'Greška pri računanju predikcija',

        /* ── My Team / pitch ── */
        gameweek:           'Kolo',
        substitutes:        'Rezervni',
        flagInjured:        'Povređen',
        flagSuspended:      'Suspendovan',
        flagUnavailable:    'Nedostupan',
        flagDoubtful:       'Neizvestan',
        gwPoints:           'Poeni Kola',
        bank:               'Budžet',
        teamValue:          'Vrednost Tima',
        captain:            'K',
        viceCaptain:        'PK',
        pts:                'poi',

        /* ── Player Database table ── */
        searchPlaceholder:  'Pretraži igrače po imenu, timu ili poziciji...',
        allPositions:       'Sve Pozicije',
        allTeams:           'Svi Timovi',
        goalkeeper:         'Golman',
        defender:           'Odbrambeni igrač',
        midfielder:         'Vezni igrač',
        forward:            'Napadač',
        colName:            'Ime',
        colTeam:            'Tim',
        colPosition:        'Pozicija',
        colPrice:           'Cena',
        colPoints:          'Poeni',
        colForm:            'Forma',
        colGoals:           'Golovi',
        colAssists:         'Asistencije',
        colXGI:             'Očekivani G+A',
        colTackles:         'Dueli',
        colOwned:           'U timu%',
        showingPlayers:     'Prikazano',
        players:            'igrača',
        noPlayersFound:     'Nema pronađenih igrača',

        /* ── Performance Analytics ── */
        perfTitle:          'Analitika Performansi',
        perfSubtitle:       'Pregled Sezone',
        gwHistory:          'Istorija Kola',
        gwPointsChart:      'Poeni po Kolu',
        totalPoints:        'Ukupni Poeni',
        overallRank:        'Ukupna Rang Lista',
        bestGW:             'Najbolje Kolo',
        worstGW:            'Najlošije Kolo',
        totalTransfers:     'Ukupno Transfera',
        rank:               'Rang',
        transfers:          'Transferi',
        gwsPlayed:          'Kola Odigrana',
        seasonStats:        'Statistike Sezone',

        /* ── Predictions ── */
        predTitle:          'Predikcija Poena',
        predSubtitle:       'Analiza Sledećih 5 Kola',
        expectedPoints:     'Očekivani Poeni',
        captainRec:         'Preporuka Kapitena',
        nextGWPredictions:  'Predikcije za Sledeće Kolo',
        topPerformers:      'Igrači s Najviše Očekivanih Poena',
        allPlayersPred:     'Svi Igrači - Očekivani Poeni',
        top3Fixture:        'Top 3 Igrača - Analiza Utakmica',
        xPts:               'oPoeni',
        form:               'Forma',
        rising:             'Raste',
        falling:            'Pada',
        stable:             'Stabilan',

        /* ── Transfers ── */
        transferTitle:      'Predlozi Transfera',
        transferSubtitle:   'Optimizuj Tvoj Tim',
        transferAnalysis:   'Analiza Transfera',
        budgetAvail:        'Dostupni Budžet',
        transfersGW:        'Transferi Ovog Kola',
        freeTransfers:      'Besplatni Transferi',
        verdictMake:        'Isplati se',
        verdictHit:         'Vredi −4',
        verdictMarginal:    'Marginalno: razmisli o čuvanju',
        alternativesNote:   'Alternative: svaka troši jedan transfer',
        sellPrice:          'prodaja',
        fixturesXPts:       'Utakmice i Projektovani Poeni',
        planTitle:          'Plan Transfera',
        planVsRoll:         'u odnosu na čuvanje transfera',
        planRoll:           'Sačuvaj transfer',
        planFT:             'BT',
        planXI:             'Tim',
        planCaptain:        'Kapiten',
        planBan:            'Nikad ne kupuj ovog igrača',
        planLockHint:       'Zaključaj igrače koje zadržavaš (nikad se ne prodaju):',
        planBanned:         'Nikad se ne kupuju (klikni da dozvoliš):',
        singleTransfers:    'Najbolji Pojedinačni Transferi',
        planNext:           'Plan',
        cardLeague:         'Mini-Liga',
        leagueSelect:       'Liga',
        leagueStandings:    'Tabela',
        leagueThreats:      'Pretnje: imaju ih rivali, ti ne (dovoljno)',
        leagueDiffs:        'Tvoji Diferencijali',
        leagueCaptains:     'Kapiteni Rivala',
        leagueTemplate:     'Šablon: ima ih pola lige ili više',
        leagueExplain:      '<strong>EO (efektivno vlasništvo)</strong> = koliko poena igrača u proseku dobija rival: 100% po vlasniku u startnih 11, 200% po kapitenu, podeljeno brojem rivala. Svaki poen igrača te pomera za <em>tvoj množilac − EO</em> u odnosu na prosečnog rivala; <strong>razlika</strong> je to puta njegovi projektovani poeni za sledeće kolo.',
        leagueBasedOn:      'Postave iz kola',
        leagueSampled:      'rivala analizirano',
        leagueTop50:        'velika liga: samo prvih 50',
        leagueNone:         'Još nisi ni u jednoj klasičnoj ligi.',
        leagueYou:          'Ti',
        leagueGap:          'Razlika',
        leagueGW:           'Kolo',
        leagueTotal:        'Ukupno',
        leagueRank:         'Mesto',
        leagueManager:      'Menadžer',
        leagueSwing:        'Razlika',
        leagueYours:        'Ti',
        leagueChips:        'Odigrani čipovi',
        errorLeague:        'Greška pri učitavanju lige',
        loadingLeague:      'Učitavanje lige...',
        leagueTopOverall:   'Najboljih {n} menadžera ukupno (ažurira se svako kolo)',
        cardFixtures:       'Analiza Rasporeda',
        fxAttack:           'Napad: očekivani golovi',
        fxDefence:          'Odbrana: čista mreža %',
        fxFdr:              'FPL težina',
        fxSortNext:         'Sortiraj po narednih',
        fxBlank:            'Bez utakmice',
        fxNone:             'Nema predstojećih utakmica.',
        fxExplain:          'Očekivani golovi i šanse za čistu mrežu dolaze iz xG za i protiv svakog tima ove sezone (uz FPL ocenu na početku) i prednosti domaćeg terena, pa razdvajaju dobru utakmicu za napadače od dobre za odbranu, što FPL težina 1–5 ne može. Dupla kola se sabiraju; kolo bez utakmice se ne računa. • = uz kvote kladionica (samo naredne utakmice).',
        fxBestAttack:       'Najbolji raspored za napad',
        fxBestDefence:      'Najbolji raspored za odbranu',
        errorFixtures:      'Greška pri učitavanju rasporeda',
        loadingFixtures:    'Učitavanje rasporeda...',
        cardOptimizer:      'AI Tim i Čipovi',
        opLoading:          'Optimizacija tima...',
        opRating:           'AI Ocena Tima',
        opRatingExplain:    'Projektovani poeni tvog tima ({range}, najboljih 11 + kapiten svako kolo) kao udeo najboljeg tima koji optimizator nađe za tvoj budžet od £{budget}m (banka + prodajne cene).',
        opPts:              'poena',
        opVsYours:          'u odnosu na tvoj tim',
        opChanges:          'izmena',
        opOut:              'Izlaze',
        opCalendar:         'Kalendar Čipova',
        opCalendarExplain:  'Vrednost svakog čipa koji još imaš, po kolu, sa tvojim trenutnim timom: Bench Boost = poeni klupe, Triple Captain = poeni kapitena još jednom, Free Hit = najbolji tim za jedno kolo minus tvojih 11. Kasnija kola pretpostavljaju da nema transfera, pa ih koristi kao smernicu. Prvi set čipova mora se iskoristiti do kola {deadline}. Najbolje kolo za svaki čip je istaknuto.',
        opNoSpecial:        'U ovom periodu još nema kola bez utakmica ni duplih kola; vrednosti čipova su slične iz kola u kolo. Dupla kola se obično pojave kada se utakmice pomere zbog kupa.',
        opXI:               'Tvojih 11',
        opDoubles:          'Dupla',
        opBlanks:           'Bez utakmice',
        opYours:            'tvojih',
        opBestWeeks:        'Najbolja kola',
        chipWildcard:       'Wildcard',
        chipFreeHit:        'Free Hit',
        chipBenchBoost:     'Bench Boost',
        chipTripleCaptain:  'Triple Captain',
        errorOptimizer:     'Greška pri optimizaciji',
        cardPrices:         'Promene Cena',
        pcExplain:          'Iz FPL-ovog predviđanja cena: napredak svakog igrača ka sledećoj promeni cene, gde +100% znači rast a −100% pad. <em>Večeras</em> je projekcija za sledeći termin promena (oko ponoći po UK vremenu). Cena se može promeniti najviše jednom dnevno. Tvoja prodajna cena raste samo za polovinu povećanja.',
        pcYourSquad:        'Tvoj Tim',
        pcSquadAlert:       'Očekuje se promena večeras',
        pcRisers:           'Verovatno poskupljuju',
        pcFallers:          'Verovatno pojeftinjuju',
        pcRose:             'Poskupeli ovog kola',
        pcFell:             'Pojeftinili ovog kola',
        pcNow:              'Sada',
        pcTonight:          'Večeras',
        pcThisGW:           'Ovo kolo',
        pcNetTransfers:     'Neto transferi',
        pcNone:             'Trenutno nijedan.',
        pcWatch:            'Prati večeras',
        errorPrices:        'Greška pri učitavanju cena',
        loadingPrices:      'Učitavanje cena...',
        cardLive:           'Kolo Uživo',
        lvInProgress:       'utakmice u toku, osvežava se svakog minuta',
        lvFinished:         'kolo završeno',
        lvBetween:          'između utakmica',
        lvNotStarted:       'još nije počelo',
        lvUpdated:          'ažurirano',
        lvExplain:          'Poeni uživo sa <strong>privremenim bonusom</strong> (*) iz sistema bonus poena dok bonus utakmice nije potvrđen, i <strong>automatskim izmenama</strong> kada se utakmice startera završe a on nije igrao (↑ ulazi, ↓ izlazi). Ukupni poeni u ligi uključuju minuse za transfere; ▲▼ je promena od početka kola.',
        lvYourTeam:         'Tvoj Tim',
        lvLeague:           'Tabela Lige Uživo',
        lvMins:             'Min',
        lvProvisional:      'privremeni bonus',
        lvPoints:           'Poeni uživo',
        errorLive:          'Greška pri učitavanju poena uživo',
        loadingLive:        'Učitavanje poena uživo...',
        accTitle:           'Tačnost Modela',
        accExplain:         'Provera na {range} ({n} igrač-kola): svako kolo se projektuje iz utakmica pre njega i poredi sa stvarno osvojenim poenima. Manja greška i veća korelacija su bolje.',
        accMae:             'Prosečna greška (poeni)',
        accCorr:            'Korelacija',
        accModel:           'Ovaj model',
        accPPG:             'Poeni po utakmici',
        accForm:            'Trenutna forma',
        accTop10:           'Top 10 igrača po projekciji modela osvojilo je u proseku <strong>{model}</strong> poena po kolu, naspram <strong>{form}</strong> za top 10 po formi.',
        gkpOptions:         'Opcije za Golmana',
        outfieldOptions:    'Opcije za Igrače',
        sortedByGain:       'Sortirano po očekivanim dobijenim poenima',
        budget:             'Budžet',
        noTransfers:        'Nema predloga transfera. Tvoj tim izgleda odlično!',
        perfectTeam:        '🎉 Savršen Tim!',
        perfectTeamDesc:    'Nisu pronađena poboljšanja. Tvoj tim je odlično optimizovan!',
        howCalc:            'Kako se predlozi računaju',
        howCalcBlock:       `<strong>Kako se izračunavaju predlozi</strong><ul style="margin:6px 0 6px 18px; padding:0;"><li><strong>Projektovani poeni po kolu</strong> za narednih 5 rokova (kolo bez utakmice donosi 0, duplo kolo računa obe utakmice). Svaka utakmica kombinuje minute (startovi i minuti u poslednjim utakmicama i u sezoni, vesti o povredama), golove i asistencije iz xG/xA per 90, čiste mreže i primljene golove iz snage timova, odbrane, defanzivni doprinos, bonus i kartone, po pravilima bodovanja ove sezone.</li><li><strong>Snaga timova</strong> se računa iz xG za i protiv svakog kluba ove sezone, uz FPL ocenu dok je uzorak mali.</li><li><strong>Dobitak</strong> = koliko se poboljšava tvojih najboljih 11 plus kapiten u tim kolima, pri čemu bliža kola više vrede. Rezervni igrač donosi poene samo ako bi startovao.</li></ul>Transferi poštuju tvoje prodajne cene (zadržavaš polovinu rasta cene), budžet i limit od 3 igrača po klubu. Svaka opcija troši jedan transfer: sa besplatnim transferom isplati se iznad ~2 poena; bez njega mora da pokrije i −4.`,
        dbStatsBlock:       `<h4>📊 Sveobuhvatne statistike igrača - 48 podataka</h4><p><strong>Kako koristiti:</strong> Skroluj horizontalno da vidiš sve kolone. Pređi mišem iznad zaglavlja za detaljna objašnjenja. Klikni na zaglavlje za sortiranje.</p><p><strong>Izvori podataka:</strong> Zvanični FPL API + Opta Sports Analytics (koriste Premier liga, FIFA, UEFA)</p><p><strong>Kategorije:</strong> Osnovne (8) • Metrike učinka (12) • Očekivane (9) • Opta napredne (7) • Mrtve lopte (3) • Trendovi transfera (4) • Analiza vrednosti (2) • Dostupnost (1)</p><p style="margin-top:8px;"><strong>Kodiranje bojama:</strong> <span class="legend-pill legend-green">Zelena = Visok učinak</span> <span class="legend-pill legend-red">Crvena = Slaba forma/povreda</span> <span class="legend-pill legend-purple">Ljubičasta = Visoki xGI</span> <span class="legend-pill legend-yellow">Žuta = Elita per 90</span> <span class="legend-pill legend-blue">Plava = ICT lider</span></p>`,
        topScorerLabel:     '🏆 VRHOVNI STRELAC',
        bestFormLabel:      '🔥 NAJBOLJA FORMA',
        mostMinsLabel:      '⏱️ NAJVIŠE MINUTA',
        mostGoalsLabel:     '⚽ NAJVIŠE GOLOVA',
        mostAssistsLabel:   '🎯 NAJVIŠE ASISTENCIJA',
        mostKeyPassLabel:   '🔑 NAJVIŠE KLJUČNIH DODAVANJA',
        mostTacklesLabel:   '🛡️ NAJVIŠE DUELA',
        bestXGILabel:       '📊 NAJBOLJI xGI',
        goalsLabel:         'golova',
        assistsLabel:       'asistencija',
        passesLabel:        'dodavanja',
        tacklesLabel:       'duela',
        transferOut:        'PRODAJ',
        transferIn:         'KUPI',
        transferReason:     'Razlog',
        transferCost:       'Cena Transfera',
        newBudget:          'Novi Budžet',
        next3Fixtures:      'Poređenje Sledećih 3 Utakmice',
        playersToWatch:     'Igrači za Praćenje',
        highPerformers:     'Igrači u formi po svim pozicijama:',
        option:             'Opcija',
        gkpFull:            'Golman',
        defFull:            'Odbrana',
        midFull:            'Vezni Red',
        fwdFull:            'Napad',
        transferSuggHeader: 'Predlozi Transfera',
        transferSuggSuffix: '',
        valueLabel:         'Vrednost',

        /* ── Player Comparison ── */
        cmpHint:            'Pretraži i odaberi do 3 igrača za poređenje FPL statistika.',
        cmpPlayer1:         'Igrač 1...',
        cmpPlayer2:         'Igrač 2...',
        cmpPlayer3:         'Igrač 3 (opcionalno)',
        cmpTitle:           'Poređenje Igrača',

        /* ── Player page ── */
        playerTitle:        'Profil Igrača',
        upcomingFixtures:   'Predstojeće Utakmice',
        recentGWPoints:     'Poeni po Poslednjem Kolu',
        last10GWs:          'Poslednjih 10 Kola',
        gwCol:              'Kolo',
        opponent:           'Protivnik',
        homeAway:           'D/G',
        score:              'Rezultat',
        mins:               'Min',
        goals:              'G',
        assists2:           'A',
        cleanSheets:        'NM',
        yellow:             'ŽK',
        ptsCol:             'Poi',
        attackStats:        'Napad',
        defenceStats:       'Odbrana',
        valueTransfers:     'Vrednost i Transferi',
        price:              'Cena',
        valueSeason:        'Vrednost (Sezona)',
        valueForm:          'Vrednost (Forma)',
        gwTransIn:          'Transferi Unutra (Kolo)',
        gwTransOut:         'Transferi Van (Kolo)',
        seasonIn:           'Sezona Unutra',

        /* ── Guardian / Onboarding ── */
        guardianSubtitle:   'Tvoj lični centar za FPL inteligenciju',
        guardianInputLabel: 'Unesi tvoj FPL Tim ID',
        guardianInputPlaceholder: 'npr. 1234567',
        guardianContinue:   'Nastavi →',
        guardianHowTitle:   'Kako pronaći Tim ID',
        guardianStep1:      'Idi na <strong>fantasy.premierleague.com</strong> i prijavi se na nalog',
        guardianStep2:      'Klikni na <strong>„Points“</strong> u gornjem navigacionom meniju',
        guardianStep3:      'Pogledaj adresnu traku — biće prikazano <code>/entry/<strong>1234567</strong>/event/1/</code>',
        guardianStep4:      'Broj između <code>/entry/</code> i <code>/event/</code> je tvoj Tim ID',
        guardianTip:        '💡 Savet: Tim ID je sedmocifreni broj vidljiv u URL adresi na stranici tvojih FPL poena.',
        changeTeamId:       'Promeni ID',
        changeTeamIdTitle:  'Promeni FPL Tim ID',
        changeTeamIdSave:   'Sačuvaj i Osveži',
        changeTeamIdCancel: 'Otkaži',

        /* ── Misc ── */
        home:               'DOMAĆIN',
        away:               'GOST',
        h:                  'D',
        a:                  'G',
        diff:               'Težina',
        vs:                 'vs',
        at:                 '@',
        average:            'Prosek',
        seasonAvg:          'Prosek Sezone',
        gwPointsLabel:      'Poeni Kola',
        noInjuryNews:       'Bez vesti o povredama',
        last:               'Poslednjih',
        gameweeks:          'Kola',
    }
};

// ── Core API ──────────────────────────────────────────────────────────────────

window.LANG = localStorage.getItem('fpl_lang') || 'en';

function t(key) {
    const dict = TRANSLATIONS[window.LANG] || TRANSLATIONS.en;
    return dict[key] !== undefined ? dict[key] : (TRANSLATIONS.en[key] || key);
}

function setLang(lang) {
    window.LANG = lang;
    localStorage.setItem('fpl_lang', lang);
    applyI18n();
    document.documentElement.lang = lang;
    _updateLangButtons();
    // Trigger full re-render if initializeApp is defined (main dashboard)
    if (typeof initializeApp === 'function') {
        // Don't re-init while the guardian/onboarding overlay is visible
        const guard = document.getElementById('fpl-guardian');
        if (guard && !guard.classList.contains('guardian-hidden')) return;
        initializeApp();
        return; // individual loaders are called inside initializeApp
    }
    // Trigger standalone page re-renders
    if (typeof loadPerformance          === 'function')  loadPerformance();
    if (typeof loadTransfers            === 'function')  loadTransfers();
    if (typeof loadTransferSuggestions  === 'function')  loadTransferSuggestions();
    if (typeof loadPredictions          === 'function')  loadPredictions();
    if (typeof loadDatabase             === 'function')  loadDatabase();
    if (typeof loadTeamPage             === 'function')  loadTeamPage();
    if (typeof loadTeam                 === 'function')  loadTeam();
    if (typeof loadPlayerPage  === 'function')  loadPlayerPage();
    if (typeof loadLeague               === 'function')  loadLeague();
    if (typeof loadFixtures             === 'function')  loadFixtures();
    if (typeof loadOptimizer            === 'function')  loadOptimizer();
    if (typeof loadPrices               === 'function')  loadPrices();
    if (typeof loadLive                 === 'function')  loadLive();
}

// Update all elements with [data-i18n] attribute
function applyI18n() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const attr = el.getAttribute('data-i18n-attr');
        const val = t(key);
        if (attr) {
            el.setAttribute(attr, val);
        } else {
            el.textContent = val;
        }
    });
    document.querySelectorAll('[data-i18n-html]').forEach(el => {
        el.innerHTML = t(el.getAttribute('data-i18n-html'));
    });
}

function _updateLangButtons() {
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('lang-btn--active', btn.dataset.lang === window.LANG);
    });
}

// Run on DOM ready
document.addEventListener('DOMContentLoaded', () => {
    document.documentElement.lang = window.LANG;
    applyI18n();
    _updateLangButtons();
});
